name: ${COMPOSE_NAME}

services:
  app:
    image: ${LEGO_CONTAINER_NAME}:${LEGO_CONTAINER_VERSION}
    build:
      context: ../images/app
      dockerfile: Dockerfile
    environment:
      LEGO_ADMIN_EMAIL: ${LEGO_ADMIN_EMAIL}
      LEGO_ACCEPT_TOS: "true"
      LEGO_DNS_PROVIDER: ${LEGO_DNS_PROVIDER}
      ${LEGO_DNS_PROVIDER_CREDENTIALS_NAME}: ${LEGO_DNS_PROVIDER_CREDENTIALS_CONTENT}
    volumes:
      - app-storage:/home/app/
    healthcheck:
      test: [ "CMD", "/bin/healthcheck.sh" ]
      start_period: 30s
      start_interval: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    restart: ${COMPOSE_RESTART_POLICY}

volumes:
  app-storage:
    name: ${LEGO_CERTS_STORAGE_NAME}
    driver: local